/* ============================================================
   MEDIA CONFIGURATION

   Every external asset path on the site is declared here, and
   nowhere else. js/media.js renders these; it never names a file.

   Personal photographs and video are NOT here - they live in
   js/assets.js and always have. Splitting them across two files
   would be exactly the scattering this module exists to prevent.

   ------------------------------------------------------------
   FORMATS

   The supplied GIFs totalled ~58 MB. None used transparency, so
   they are converted to MP4 by tools/build-external.sh and come
   out around 20x smaller - 3.7 MB for the whole library. A GIF is
   256 colours decoded frame-by-frame on the CPU; an MP4 keeps
   full colour and is decoded by video hardware.

   The cut-outs stay as WebP-with-alpha, because their transparent
   background is the entire point: the hookah has to stand on the
   game's own backdrop, the diving objects have to sit in water.

   ------------------------------------------------------------
   MISSING FILES ARE FINE

   Any slot may point at a file that does not exist, or be set to
   null. The element removes itself, leaving no gap and no broken
   image icon. Decorative media can never break a section.
   ============================================================ */

const BACKGROUNDS = '/assets/external/backgrounds';
const REACTIONS = '/assets/external/reactions';
const TMNT = '/assets/external/tmnt';
const SURRON = '/assets/external/surron';
const HOOKAH = '/assets/external/hookah';
const DIVING = '/assets/external/diving';
const GIFT = '/assets/external/gift';

const clip = (src, note) => ({ kind: 'video', src, note });
const cutout = (base, note) => ({ kind: 'image', src: `${base}.webp`, fallback: `${base}.png`, note });
/* Opaque scene photographs. JPEG rather than PNG behind the WebP,
   because there is no alpha to preserve. */
const bg = (base, note) => ({ kind: 'image', src: `${base}.webp`, fallback: `${base}.jpg`, note });

/* ------------------------------------------------------------
   THE LIBRARY
   `note` describes what is actually in the file, so the mapping
   below can be re-shuffled without opening each clip.
   ------------------------------------------------------------ */
export const ASSETS = {
  /* --- reactions --- */
  reaction1: clip(`${REACTIONS}/reaction1.mp4`, 'парень в наушниках, задумчиво подпёр подбородок'),
  reaction2: clip(`${REACTIONS}/reaction2.mp4`, 'девушка ухмыляется, ч/б'),
  reaction3: clip(`${REACTIONS}/reaction3.mp4`, 'резкий наезд камеры на глаз'),
  absurd1: clip(`${REACTIONS}/absurd1.mp4`, 'руки на лице, полный шок'),
  absurd2: clip(`${REACTIONS}/absurd2.mp4`, 'чёрный кот и спиннер загрузки'),
  celebration1: clip(`${REACTIONS}/celebration1.mp4`, 'мужчина сложил руки, доволен'),
  celebration2: clip(`${REACTIONS}/celebration2.mp4`, 'пережатый глитч-мем'),
  fail1: clip(`${REACTIONS}/fail1.mp4`, 'прыжок на мотоцикле в воду'),
  fail2: clip(`${REACTIONS}/fail2.mp4`, 'мужик падает спиной в дверной проём'),

  /* --- procedural, generated by tools/build-external.sh --- */
  static: clip(`${REACTIONS}/static.mp4`, 'помехи мёртвого канала'),
  glitch: clip(`${REACTIONS}/glitch.mp4`, 'разрыв строк'),
  pulse: clip(`${REACTIONS}/pulse.mp4`, 'кардиограмма'),

  /* --- TMNT --- */
  tmnt1: clip(`${TMNT}/tmnt1.mp4`, 'Микеланджело, крупный план, ухмылка'),
  tmnt2: clip(`${TMNT}/tmnt2.mp4`, 'Донателло смотрит в кадр'),
  tmnt3: clip(`${TMNT}/tmnt3.mp4`, 'пиксельная черепашка со звёздами'),
  tmntReveal: clip(`${TMNT}/reveal.mp4`, 'человек выходит из-за красного занавеса'),

  /* --- objects --- */
  hookah: cutout(`${HOOKAH}/hookah`, 'кальян, вырезан по контуру'),
  revo: cutout(`${DIVING}/revo`, 'банка Revo'),
  keys: cutout(`${DIVING}/keys`, 'два ключа на кольце'),
  earring: cutout(`${DIVING}/earring`, 'золотые серьги-кольца'),
  present: cutout(`${GIFT}/present`, 'защитный панцирь Leatt - настоящий подарок'),

  /* The main bike. Replaced with a higher-quality file under the
     same name, so this entry is unchanged - but the build had to be
     re-run for the new pixels to reach the site. Used both in the
     showcase and as the rider in the Sur-Ron game. */
  surronSilhouette: cutout(`${SURRON}/silhouette`, 'Sur-Ron Light Bee X, вид сбоку'),

  /* --- one scene behind each mini-game ---
     Opaque photographs, not cut-outs. Each is used by exactly one
     game and nowhere else on the site. They are mounted as a CSS
     layer underneath the canvas rather than drawn into it, so they
     cost nothing per frame and cannot touch collision or hit tests. */
  bgCoal: bg(`${BACKGROUNDS}/hookah`, 'неоновая вывеска бара, ВНЕ ВРЕМЕНИ'),
  bgSurron: bg(`${BACKGROUNDS}/surron`, 'ночной въездной знак КОЦЮБИНСЬКЕ в зелёном неоне'),
  bgDiving: bg(`${BACKGROUNDS}/diving`, 'песчаное дно и поверхность воды сверху'),

  /* The campaign poster: multiple views plus printed specifications.
     Opaque, so it is a jpg rather than a cut-out. */
  surronShowcase: {
    kind: 'image',
    src: `${SURRON}/showcase.webp`,
    fallback: `${SURRON}/showcase.jpg`,
    note: 'постер Sur-Ron Light Bee X со спецификациями',
  },
};

/* ------------------------------------------------------------
   PLACEMENTS

   slot -> which asset appears there, and how it behaves.

   `loops`  how many times it plays before freezing on its last
            frame. A reaction that repeats forever stops being a
            punchline and becomes wallpaper, so most are 2-3.
            0 means loop indefinitely (used only for the loading
            spinner, which is meant to be tedious).
   `size`   sm | md | lg - see .moment--sm/md/lg in main.css.

   Swap any line freely; nothing else needs to change.
   ------------------------------------------------------------ */
export const PLACEMENTS = {
  /* 01 intro - beside "ебнутость 146%" */
  'intro-overload': { asset: 'absurd2', loops: 0, size: 'sm' },

  /* 03 archive */
  'archive-2022': { asset: 'reaction3', loops: 2, size: 'md' },
  'void-2024-signal': { asset: 'static', loops: 0, size: 'band' },
  'void-2024': { asset: 'reaction1', loops: 2, size: 'sm' },
  'void-2025-signal': { asset: 'glitch', loops: 0, size: 'band' },
  'void-2025': { asset: 'celebration2', loops: 3, size: 'sm' },

  /* 05 statistics */
  'stat-injuries-trace': { asset: 'pulse', loops: 0, size: 'trace' },
  'stat-injuries': { asset: 'fail1', loops: 2, size: 'md' },

  /* 06 games - shown on the result overlay */
  'coal-win': { asset: 'reaction2', loops: 2, size: 'md' },
  'coal-lose': { asset: 'fail2', loops: 2, size: 'md' },
  'surron-win': { asset: 'celebration1', loops: 2, size: 'md' },
  'surron-lose': { asset: 'absurd1', loops: 2, size: 'md' },
  /* Diving deliberately has none: recovering all three already
     triggers the surfacing transition, which is its payoff. A GIF
     on top would talk over it. Set an asset here to add one. */
  'diving-win': null,

  /* 08 gift */
  'gift-intro': { asset: 'tmnt2', loops: 2, size: 'md' },
  'gift-hype': { asset: 'tmnt1', loops: 4, size: 'sm' },
  'gift-reveal': { asset: 'tmntReveal', loops: 1, size: 'lg' },
  'gift-outro': { asset: 'tmnt3', loops: 3, size: 'md' },
};

/* Look up a placement and resolve it to a concrete asset. Returns
   null for an unknown or deliberately empty slot. */
export function resolve(slot) {
  const p = PLACEMENTS[slot];
  if (!p) return null;
  const asset = ASSETS[p.asset];
  if (!asset) return null;
  return { ...asset, loops: p.loops ?? 2, size: p.size || 'md', slot };
}

/* Direct access for code that needs a specific file rather than a
   placement - the games drawing into canvas, mostly. */
export const asset = (name) => ASSETS[name] || null;
