#!/usr/bin/env bash
#
# Turn the camera originals into web-ready assets.
#
#     bash tools/build-assets.sh
#
# Sources live OUTSIDE the repo (they are 680 MB - far too much to
# commit). Point SRC at wherever they sit:
#
#     SRC="/mnt/c/Users/Volodka/Desktop/miracle" bash tools/build-assets.sh
#
# Outputs go to assets/photos/ and assets/videos/ and ARE committed.
# Re-running overwrites them. Originals are never modified.

set -euo pipefail

SRC="${SRC:-/mnt/c/Users/Volodka/Desktop/miracle}"
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
photos="$repo/assets/photos"
videos="$repo/assets/videos"

command -v ffmpeg >/dev/null || { echo "ffmpeg not installed. Run: sudo apt install ffmpeg" >&2; exit 1; }
[[ -d "$SRC" ]] || { echo "source folder not found: $SRC" >&2; exit 1; }

mkdir -p "$photos" "$videos"

# Longest side for stills. The archive shows images large but never
# beyond roughly half a 4K viewport, so 1600 is generous.
MAX=1600

lower() { echo "$1" | tr 'A-Z' 'a-z'; }

# ---------------------------------------------------------------
# Stills: JPG and HEIC -> optimised .jpg plus a .webp alongside.
#
# HEIC is the important one. It is Apple's default camera format and
# NO browser except Safari can display it - Chrome and Firefox show
# nothing at all. Converting is not an optimisation here, it is what
# makes the picture appear.
#
# Both formats are written so the page can offer webp first and fall
# back to jpg. webp is roughly 30% smaller at the same quality.
# ---------------------------------------------------------------
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

for f in "$SRC"/*.JPG "$SRC"/*.HEIC; do
  [[ -e "$f" ]] || continue
  base="$(lower "$(basename "${f%.*}")")"

  # scale='if(gt(iw,ih),MAX,-2)':'if(gt(iw,ih),-2,MAX)'
  #   Fit the LONGEST side to MAX whichever way round the photo is,
  #   and never enlarge a photo that is already smaller.
  vf="scale='if(gt(iw,ih),min(iw,$MAX),-2)':'if(gt(iw,ih),-2,min(ih,$MAX))'"

  # A HEIC stores the picture as a grid of tiles which ffmpeg stitches
  # using an internal complex filtergraph - and a stream fed by one of
  # those cannot also take a -vf. So HEICs are decoded whole first,
  # then scaled from the decoded copy. JPEGs go straight through.
  in="$f"
  if [[ "${f##*.}" == "HEIC" ]]; then
    in="$tmp/$base.png"
    ffmpeg -y -loglevel error -i "$f" -frames:v 1 -update 1 "$in"
  fi

  ffmpeg -y -loglevel error -i "$in" -frames:v 1 -update 1 -vf "$vf" \
         -q:v 4 "$photos/$base.jpg"
  # NOTE: this ffmpeg build IGNORES -quality for libwebp - every value
  # from 10 to 95 produced a byte-identical file. -qscale:v is the flag
  # that actually controls it (higher = better).
  ffmpeg -y -loglevel error -i "$in" -frames:v 1 -update 1 -vf "$vf" \
         -c:v libwebp -qscale:v 76 "$photos/$base.webp"
  echo "  photo  $base"
done

# ---------------------------------------------------------------
# Video: 4K originals (39-147 MB) -> web clips.
#
# These are background/montage footage that is scaled, cropped and
# often partly covered by type. 4K is pointless there and one 147 MB
# file would exceed GitHub's 100 MB per-file hard limit anyway.
#
# -an drops audio: every one of these plays muted behind other
#   content, and an unused audio track is just weight.
# -maxrate/-bufsize cap the bitrate so sizes stay predictable
#   instead of spiking on high-motion shots.
# ---------------------------------------------------------------
for f in "$SRC"/*.MOV "$SRC"/*.MP4; do
  [[ -e "$f" ]] || continue
  base="$(lower "$(basename "${f%.*}")")"

  ffmpeg -y -loglevel error -i "$f" \
    -map 0:v:0 \
    -vf "scale='if(gt(iw,ih),min(iw,1280),-2)':'if(gt(iw,ih),-2,min(ih,1280))'" \
    -c:v libx264 -crf 28 -preset slow -profile:v high -pix_fmt yuv420p \
    -maxrate 1800k -bufsize 3600k -an -movflags +faststart \
    "$videos/$base.mp4"

  # Poster: shown while the clip loads, and used as the still fallback
  # when a browser refuses to autoplay.
  ffmpeg -y -loglevel error -ss 0.5 -i "$videos/$base.mp4" \
    -frames:v 1 -update 1 -vf "scale=720:-2" -q:v 5 \
    "$videos/$base-poster.jpg"
  echo "  video  $base"
done

# ---------------------------------------------------------------
# Dimension manifest.
#
# Every <img> needs width and height BEFORE the file arrives, or the
# browser reserves no space for it: the picture pops in on load and
# shoves everything below it down the page. On a site that is one
# long scroll through photographs that means the reader loses their
# place constantly, and any pinned scroll animation is measuring a
# height that is still changing underneath it.
#
# So the real pixel size of every asset is written out here as a
# generated module, and js/dom.js stamps it onto each element.
# ---------------------------------------------------------------
manifest="$repo/js/asset-manifest.js"
{
  echo "/* GENERATED by tools/build-assets.sh - do not edit by hand."
  echo "   Intrinsic pixel size of every asset, so the page can reserve"
  echo "   space before the file downloads. Re-run the script to update. */"
  echo
  echo "export const SIZES = {"
  for f in "$photos"/*.jpg "$videos"/*.mp4; do
    [[ -e "$f" ]] || continue
    key="$(basename "${f%.*}")"
    dim=$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height \
                  -of csv=p=0 "$f" 2>/dev/null | head -1)
    w="${dim%,*}"; h="${dim#*,}"
    [[ -n "$w" && -n "$h" ]] && echo "  '$key': [$w, $h],"
  done
  echo "};"
} > "$manifest"

echo
echo "photos: $(ls "$photos" | wc -l) files, $(du -sh "$photos" | cut -f1)"
echo "videos: $(ls "$videos" | wc -l) files, $(du -sh "$videos" | cut -f1)"
echo "manifest: $(grep -c "': \[" "$manifest") entries -> js/asset-manifest.js"
